---
version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    tty: true
    container_name: db-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    env_file:
      - Docker/config/db-mongo.conf
    networks:
      - main
    command: ["--bind_ip", "0.0.0.0"]

  postgres:
    image: postgres:13
    container_name: db-postgres
    restart: always
    env_file: Docker/config/db-postgres.conf
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodemo:
    restart: always
    container_name: backend-mongodemo
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Docker/config/db-mongo.conf
    ports:
      - 8080:8080
    networks:
      - main
    depends_on:
      - postgres
      - mongodb

networks:
  main:
    driver: bridge

volumes:
  mongo-data:
  postgres_data:
