-- public.accidents definition

-- Drop table

-- DROP TABLE public.accidents;

CREATE TABLE public.accidents (
	id varchar(255) NULL,
	"source" varchar(255) NULL,
	tmc float4 NULL,
	severity int4 NULL,
	start_time varchar(255) NULL,
	end_time varchar(255) NULL,
	start_lat float4 NULL,
	start_lng float4 NULL,
	end_lat varchar(255) NULL,
	end_lng varchar(255) NULL,
	distance float4 NULL,
	description text NULL,
	street varchar(255) NULL,
	side varchar(255) NULL,
	city varchar(255) NULL,
	county varchar(255) NULL,
	state varchar(255) NULL,
	zipcode varchar(255) NULL,
	country varchar(255) NULL,
	timezone varchar(255) NULL,
	airport_code varchar(255) NULL,
	weather_timestamp timestamp NULL,
	temperature float4 NULL,
	wind_chill float4 NULL,
	humidity float4 NULL,
	pressure float4 NULL,
	visibility float4 NULL,
	wind_direction varchar(255) NULL,
	wind_speed float4 NULL,
	precipitation float4 NULL,
	weather_condition varchar(255) NULL,
	amenity bool NULL,
	bump bool NULL,
	crossing bool NULL,
	give_way bool NULL,
	junction bool NULL,
	no_exit bool NULL,
	railway bool NULL,
	roundabout bool NULL,
	station bool NULL,
	stop bool NULL,
	traffic_calming bool NULL,
	traffic_signal bool NULL,
	turning_loop bool NULL,
	sunrise_sunset varchar(255) NULL,
	civil_twilight varchar(255) NULL,
	nautical_twilight varchar(255) NULL,
	astronomical_twilight varchar(255) NULL,
	"Number" float4 NULL
);